service: booktock-backend
frameworkVersion: "3"

plugins:
  - serverless-prune-plugin
  - serverless-plugin-typescript
  - serverless-dynamodb-local
  - serverless-offline
  - serverless-layers

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221
  stage: ${opt:stage, self:custom.defaultStage}
  region: ap-northeast-1
  deploymentBucket:
    name: booktock-deployment-bucket-${self:provider.stage}
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
            - dynamodb:Scan
          Resource: arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.DYNAMODB_SAMPLE_TABLE}
  environment:
    STAGE: ${self:provider.stage}
    DYNAMODB_SAMPLE_TABLE: ${self:service}-${self:provider.stage}-sample

functions:
  saveSample:
    handler: handler.saveSample
    events:
      - http:
          path: /api/v1/samples
          method: post
  getAllSamples:
    handler: handler.getAllSamples
    events:
      - http:
          path: /api/v1/samples
          method: get

resources:
  Resources:
    SampleTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.DYNAMODB_SAMPLE_TABLE}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PROVISIONED
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

custom:
  defaultStage: local
  prune:
    automatic: true
    number: 3
  serverless-layers:
    compatibleRuntimes: ["nodejs14.x"]
  dynamodb:
    stages:
      - local
    start:
      # docker: true
      port: 8000
      inMemory: true
      migrate: true
      seed: false
      sharedDb: true
      # convertEmptyValues: true
      # Uncomment only if you already have a DynamoDB running locally
      # noStart: true
