service: booktock-backend
frameworkVersion: "3"

plugins:
  - serverless-prune-plugin
  - serverless-plugin-typescript
  - serverless-offline
  - serverless-layers

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221
  stage: ${opt:stage, self:custom.defaultStage}
  region: ap-northeast-1
  deploymentBucket:
    name: booktock-deployment-bucket-${self:provider.stage}
  environment:
    STAGE: ${self:provider.stage}

functions:
  saveSample:
    handler: handler.saveSample
    events:
      - http:
          path: /api/v1/samples
          method: post
  getSamples:
    handler: handler.getSamples
    events:
      - http:
          path: /api/v1/samples
          method: get

custom:
  defaultStage: local
  prune:
    automatic: true
    number: 3
  serverless-layers:
    compatibleRuntimes: ["nodejs14.x"]
