version: "3.7"
services:
  db:
    container_name: booktock-db
    image: postgres:13.5
    ports:
      - 5432:5432
    volumes:
      - booktock-store:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: booktock
      POSTGRES_DB: booktock
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
      TZ: "Asia/Tokyo"

volumes:
  booktock-store:
    driver: local
